Block team 8 build 24-2 6, team 30 build 15
Both are causing:
java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER